branch24
ZdrzalikPrzemyslaw/zzpj-czat pull request #52
Opened 2021-05-15 11:29 UTC by Yarvi

Nie jestem pewien czy o to chodziło i czy jest dobrze jak coś.

2021-05-15 12:07 UTC, ZdrzalikPrzemyslaw requested changes
Metoda menageera nie powinna przyjmować encji w stanei deatached tylko jakieś odwołanei do encji, najlepiej uinikalny username i pobierać encje już w metodzie menagera

2021-05-16 14:31 UTC, JuliaSzymanska approved these changes

2021-05-16 14:32 UTC, JuliaSzymanska approved these changes

2021-05-16 14:32 UTC, ZdrzalikPrzemyslaw approved these changes

2021-05-16 14:32 UTC, merged